export const DHIS_PROGRAM = "KdYt2OP9VjD";
export const DHIS2_ROOT_ORG = "GRcUwrSIcZv";

export const DHIS2_ACTIVE_RETREATS_SQL_VIEW = "NyBDf8X8UxG";
export const DHIS_RETREATS_OPTION_SET_ID = "ys2Pv9hTS0O";
export const DHIS_RETREAT_SELECTION_STATE_OPTION_SET_ID = "ECk38BLpbn9";

export const DHIS_RETREAT_TYPE_OPTION_SET_ID = "Mk6tBQBCuGY";

export const DHIS2_RETREAT_DATE_ATTRIBUTE = "sCzsZZ7m37E";
export const DHIS2_RETREAT_DISABLED_ATTRIBUTE = "hp92k6RhLJS";
export const DHIS2_RETREAT_LOCATION_ATTRIBUTE = "TuaBW7iXTGw";
export const DHIS2_RETREAT_TOTAL_YOGIS_ATTRIBUTE = "DkyFJvcKgL2";
export const DHIS2_RETREAT_NO_OF_DAYS_ATTRIBUTE = "vl3IQiIavWD";
export const DHIS2_RETREAT_TYPE_ATTRIBUTE = "AJZR2ji582g";
export const DHIS2_RETREAT_CODE_ATTRIBUTE = "lzIri3GkWM2";
export const DHIS2_RETREAT_MEDIUM_ATTRIBUTE = "E6fhBET5Xwj";

export const DHIS2_EXPRESSION_OF_INTEREST_PROGRAM_STAGE = "BLn1j2VgLZf";
export const DHIS2_RETREAT_DATA_ELEMENT = "rYqV3VQu7LS";
export const DHIS2_RETREAT_SELECTION_STATE_DATA_ELEMENT = "MVaziT78i7p";
export const DHIS2_RETREAT_SELECTION_STATE_SELECTED_CODE = "selected";

export const DHIS2_SPECIAL_COMMENT_PROGRAM_STAGE = "owqAYpdS5dr";
export const DHIS2_SPECIAL_COMMENT_DATA_ELEMENT = "PH2ygv78F19";

export const DHIS2_PARTICIPATION_PROGRAM_STAGE = "NYxnKQd6goA";
export const DHIS2_ATTENDANCE_DATA_ELEMENT = "CzwVwJ30hTj";
export const DHIS2_ROOM_ALLOCATION_DATA_ELEMENT = "WOaAAkIYoL7";

export const DHIS2_ROOMS_OPTION_SET_ID = "ofMFrZQtp9g";
export const DHIS2_ROOMS_FLOOR_ATTRIBUTE = "tAqOHVVVy2X";

export const DHIS2_LANGUAGES_OPTION_SET_ID = "oLXJxrV9jWm";

export const DHIS2_TEI_ATTRIBUTE_FULL_NAME = "fvk2p04ylAA";
export const DHIS2_TEI_ATTRIBUTE_GENDER = "tuKFO1uF5x5";
export const DHIS2_TEI_ATTRIBUTE_MOBILE = "lLXB9cYYgEP";
export const DHIS2_TEI_ATTRIBUTE_MARITAL_STATE = "B08mfPKrUiM";
export const DHIS2_TEI_ATTRIBUTE_NIC = "W1fmUMMnQdu";
export const DHIS2_TEI_ATTRIBUTE_PASSPORT = "hv3aLM80Mrn";
export const DHIS2_TEI_ATTRIBUTE_DOB = "oZkvTN1dcPw";
export const DHIS2_TEI_ATTRIBUTE_YOGI_PRIORITY = "USvWZzFFKKn";

export const DHIS2_TEI_ATTRIBUTE_HAS_KIDS = "Bpce3m4do80";
export const DHIS2_TEI_ATTRIBUTE_HAS_KIDS_COMMENT = "i3RptmIeSwR";

export const DHIS2_TEI_ATTRIBUTE_HAS_PERMISSION = "QGXYhZMXfnc";
export const DHIS2_TEI_ATTRIBUTE_HAS_PERMISSION_COMMENT = "QOGamVcvLPz";

export const DHIS2_TEI_ATTRIBUTE_HAS_UNATTENDED_DEFORMITIES = "RpNKpAufHbn";
export const DHIS2_TEI_ATTRIBUTE_HAS_UNATTENDED_DEFORMITIES_COMMENT = "HtW0OMmthFQ";

export const DHIS2_TEI_ATTRIBUTE_HAS_STRESS = "dgky5acnvG3";
export const DHIS2_TEI_ATTRIBUTE_HAS_STRESS_COMMENT = "Mp6LLGv4WOT";
