import React from "react";
import { useDataMutation, useDataQuery } from "@dhis2/app-runtime";
import { observer } from "mobx-react";
import {
  Button,
  ButtonStrip,
  CircularLoader,
  InputFieldFF,
  Label,
  Modal,
  ModalActions,
  ModalContent,
  ModalTitle,
  NoticeBox,
  OrganisationUnitTree,
  ReactFinalForm,
  SingleSelectFieldFF,
  hasValue,
  SwitchFieldFF,
} from "@dhis2/ui";
import {
  DHIS2_RETREAT_ATTRIBUTE_ACCOMMODATION_NOT_PROVIDED,
  DHIS2_RETREAT_ATTRIBUTE_ACCOMMODATION_OPTIONAL,
  DHIS2_RETREAT_ATTRIBUTE_PRIVATE,
  DHIS2_RETREAT_CLERGY_ONLY_ATTRIBUTE,
  DHIS2_RETREAT_CODE_ATTRIBUTE,
  DHIS2_RETREAT_DATE_ATTRIBUTE,
  DHIS2_RETREAT_DISABLED_ATTRIBUTE,
  DHIS2_RETREAT_LOCATION_ATTRIBUTE,
  DHIS2_RETREAT_MEDIUM_ATTRIBUTE,
  DHIS2_RETREAT_NO_OF_DAYS_ATTRIBUTE,
  DHIS2_RETREAT_TOTAL_YOGIS_ATTRIBUTE,
  DHIS2_RETREAT_TYPE_ATTRIBUTE,
  DHIS2_ROOT_ORG,
  DHIS_RETREATS_OPTION_SET_ID,
} from "../dhis2";
import { useStore } from "../stores/StoreProvider";

const { Form, Field, FormSpy } = ReactFinalForm;

const styles = {
  fieldRow: {
    marginBottom: 10,
  },
};

const optionMutation = {
  resource: "options",
  data: ({ code, name, attributeValues }) => ({
    code,
    name,
    optionSet: { id: DHIS_RETREATS_OPTION_SET_ID },
    attributeValues,
  }),
  type: "create",
};

const updateMutation = {
  resource: "options",
  id: ({ id }) => id,
  data: ({ code, name, attributeValues }) => ({
    code,
    name,
    optionSet: { id: DHIS_RETREATS_OPTION_SET_ID },
    attributeValues,
  }),
  type: "update",
};

const editDataQuery = {
  option: {
    resource: "options",
    id: ({ id }) => id,
    params: {
      fields: "attributeValues[attribute[id],value],name,code",
    },
  },
  orgUnit: {
    resource: "organisationUnits",
    id: ({ locationId }) => locationId,
    params: {
      fields: "id,path,displayName",
    },
  },
};

const RetreatModel = observer(({ onCancel, retreat }) => {
  const store = useStore();

  const { data: editData, loading: editLoading } = useDataQuery(editDataQuery, {
    variables: { id: retreat?.id, locationId: retreat?.location },
    lazy: !retreat,
  });

  const [create, { loading: creating, error: createError }] = useDataMutation(
    optionMutation,
    {
      onComplete: () => {
        onCancel();
        store.metadata.loadRetreats();
      },
    },
  );

  const [update, { loading: updating, error: updateError }] = useDataMutation(
    updateMutation,
    {
      onComplete: () => {
        onCancel();
        store.metadata.loadRetreats();
      },
    },
  );

  const initialValues = React.useMemo(() => {
    if (!retreat || !editData) return {};
    const attrs = editData.option.attributeValues;
    const getValue = (id) => attrs.find((a) => a.attribute.id === id)?.value;
    const getBoolValue = (id) => getValue(id) === "true";

    const name = editData.option.name;
    const date = getValue(DHIS2_RETREAT_DATE_ATTRIBUTE);

    // Check if name matches the generated pattern (Date + Location)
    // We recreate the generated pattern to check
    const generatedName =
      date && editData.orgUnit
        ? `${new Date(date)
            .toLocaleDateString("en-US", {
              year: "numeric",
              month: "short",
              day: "numeric",
            })
            .replace(",", "")} ${editData.orgUnit.displayName}`
        : "";

    const isAutoGenerated = !retreat || name === generatedName; // Default to true for new, or if matches

    return {
      autoGenerateName: isAutoGenerated,
      name: name,
      code: getValue(DHIS2_RETREAT_CODE_ATTRIBUTE),
      date: getValue(DHIS2_RETREAT_DATE_ATTRIBUTE)?.split("T")[0],
      noOfDays: getValue(DHIS2_RETREAT_NO_OF_DAYS_ATTRIBUTE),
      noOfYogis: getValue(DHIS2_RETREAT_TOTAL_YOGIS_ATTRIBUTE),
      retreatType: getValue(DHIS2_RETREAT_TYPE_ATTRIBUTE),
      location: editData.orgUnit,
      medium: getValue(DHIS2_RETREAT_MEDIUM_ATTRIBUTE),
      clergyOnly: getBoolValue(DHIS2_RETREAT_CLERGY_ONLY_ATTRIBUTE),
      privateRetreat: getBoolValue(DHIS2_RETREAT_ATTRIBUTE_PRIVATE),
      accomodationNotProvided: getBoolValue(
        DHIS2_RETREAT_ATTRIBUTE_ACCOMMODATION_NOT_PROVIDED,
      ),
      accomodationOptional: getBoolValue(
        DHIS2_RETREAT_ATTRIBUTE_ACCOMMODATION_OPTIONAL,
      ),
      disabled: getBoolValue(DHIS2_RETREAT_DISABLED_ATTRIBUTE),
    };
  }, [editData, retreat]);

  const loading = creating || updating || editLoading;

  if (retreat && editLoading) {
    return (
      <Modal>
        <ModalTitle>Edit Retreat</ModalTitle>
        <ModalContent>
          <div
            style={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              height: 200,
            }}
          >
            <CircularLoader />
          </div>
        </ModalContent>
      </Modal>
    );
  }

  const error = createError || updateError;

  return (
    <Form
      initialValues={initialValues}
      onSubmit={(values) => {
        const attributeValues = [
          {
            attribute: { id: DHIS2_RETREAT_DATE_ATTRIBUTE },
            value: values.date,
          },
          {
            attribute: { id: DHIS2_RETREAT_LOCATION_ATTRIBUTE },
            value: values.location.id,
          },
          {
            attribute: { id: DHIS2_RETREAT_NO_OF_DAYS_ATTRIBUTE },
            value: values.noOfDays,
          },
          {
            attribute: { id: DHIS2_RETREAT_TOTAL_YOGIS_ATTRIBUTE },
            value: values.noOfYogis,
          },
          {
            attribute: { id: DHIS2_RETREAT_TYPE_ATTRIBUTE },
            value: values.retreatType,
          },
          {
            attribute: { id: DHIS2_RETREAT_DISABLED_ATTRIBUTE },
            value: values.disabled || false,
          },
          {
            attribute: { id: DHIS2_RETREAT_CODE_ATTRIBUTE },
            value: values.code,
          },
          {
            attribute: { id: DHIS2_RETREAT_MEDIUM_ATTRIBUTE },
            value: values.medium,
          },
          {
            attribute: {
              id: DHIS2_RETREAT_CLERGY_ONLY_ATTRIBUTE,
            },
            value: values.clergyOnly,
          },
          {
            attribute: {
              id: DHIS2_RETREAT_ATTRIBUTE_PRIVATE,
            },
            value: values.privateRetreat,
          },
          {
            attribute: {
              id: DHIS2_RETREAT_ATTRIBUTE_ACCOMMODATION_NOT_PROVIDED,
            },
            value: values.accomodationNotProvided,
          },
          {
            attribute: {
              id: DHIS2_RETREAT_ATTRIBUTE_ACCOMMODATION_OPTIONAL,
            },
            value: values.accomodationOptional,
          },
        ];

        let generatedString = `${new Date(values.date)
          .toLocaleDateString("en-US", {
            year: "numeric",
            month: "short",
            day: "numeric",
          })
          .replace(",", "")} ${values.location?.displayName}`;

        let optionName = values.autoGenerateName
          ? generatedString
          : values.name;

        if (retreat) {
          // DHIS2 Option Code should never be changed for existing retreats
          update({
            id: retreat.id,
            name: optionName,
            code: retreat.code,
            attributeValues,
          });
        } else {
          create({ name: optionName, code: generatedString, attributeValues });
        }
      }}
    >
      {({ handleSubmit, form, submitting, values }) => (
        <form>
          <FormSpy
            subscription={{ values: true }}
            onChange={({ values }) => {
              if (values.autoGenerateName && values.date && values.location) {
                const generatedName = `${new Date(values.date)
                  .toLocaleDateString("en-US", {
                    year: "numeric",
                    month: "short",
                    day: "numeric",
                  })
                  .replace(",", "")} ${values.location.displayName}`;

                if (values.name !== generatedName) {
                  form.change("name", generatedName);
                }
              }
            }}
          />
          <Modal>
            <ModalTitle>{retreat ? "Edit Retreat" : "New Retreat"}</ModalTitle>
            <ModalContent>
              <div style={styles.fieldRow}>
                <Field
                  name="name"
                  label="Retreat Name"
                  component={InputFieldFF}
                  type="text"
                  validate={hasValue}
                  disabled={values.autoGenerateName}
                />
              </div>
              <div style={styles.fieldRow}>
                <Field
                  type="checkbox"
                  name="autoGenerateName"
                  label="Auto Generate Name"
                  defaultValue={true}
                  component={SwitchFieldFF}
                />
              </div>
              <div style={styles.fieldRow}>
                <Field
                  required
                  name="code"
                  label="Code"
                  placeholder="5GS1"
                  component={InputFieldFF}
                  type="text"
                  validate={hasValue}
                />
              </div>
              <div style={styles.fieldRow}>
                <Field
                  required
                  name="date"
                  label="Date"
                  component={InputFieldFF}
                  type="date"
                  validate={hasValue}
                />
              </div>
              <div style={styles.fieldRow}>
                <Field
                  required
                  name="noOfDays"
                  label="No of Days"
                  component={InputFieldFF}
                  type="number"
                  validate={hasValue}
                />
              </div>
              <div style={styles.fieldRow}>
                <Field
                  name="location"
                  label="Location"
                  validate={hasValue}
                  required
                >
                  {(props) => (
                    <div>
                      <Label required>Location</Label>
                      <OrganisationUnitTree
                        roots={DHIS2_ROOT_ORG}
                        onChange={(e) => {
                          props.input.onChange(e);
                        }}
                        autoExpandLoadingError={true}
                        selected={
                          props.input.value ? [props.input.value.path] : []
                        }
                      />
                    </div>
                  )}
                </Field>
              </div>
              <div style={styles.fieldRow}>
                <Field
                  required
                  name="noOfYogis"
                  label="No of Yogis"
                  component={InputFieldFF}
                  type="number"
                  validate={hasValue}
                />
              </div>
              <div style={styles.fieldRow}>
                <Field
                  required
                  name="medium"
                  label="Medium"
                  component={SingleSelectFieldFF}
                  type="number"
                  defaultValue="sinhala"
                  validate={hasValue}
                  options={store.metadata.languages.map((option) => {
                    return {
                      label: option.name,
                      value: option.code,
                    };
                  })}
                />
              </div>
              <div style={styles.fieldRow}>
                <Field
                  required
                  name="retreatType"
                  label="Retreat Type"
                  component={SingleSelectFieldFF}
                  validate={hasValue}
                  options={store.metadata.retreatTypes.map((option) => {
                    return {
                      label: option.name,
                      value: option.code,
                    };
                  })}
                />
              </div>
              <div style={styles.fieldRow}>
                <Field
                  type="checkbox"
                  name="clergyOnly"
                  label="Only for Clergy"
                  defaultValue={false}
                  component={SwitchFieldFF}
                />
              </div>
              <div style={styles.fieldRow}>
                <Field
                  type="checkbox"
                  name="privateRetreat"
                  label="Private Retreat"
                  defaultValue={false}
                  component={SwitchFieldFF}
                />
              </div>
              <div style={styles.fieldRow}>
                <Field
                  type="checkbox"
                  name="accomodationNotProvided"
                  label="Accommodation Not Provided (Travel from home)"
                  defaultValue={false}
                >
                  {({ input, meta }) => (
                    <SwitchFieldFF
                      input={{
                        ...input,
                        onChange: (e) => {
                          input.onChange(e);
                          if (e.target.checked) {
                            form.change("accomodationOptional", false);
                          }
                        },
                      }}
                      meta={meta}
                      label="Accommodation Not Provided (Travel from home)"
                    />
                  )}
                </Field>
              </div>
              <div style={styles.fieldRow}>
                <Field
                  type="checkbox"
                  name="accomodationOptional"
                  label="Accommodation Optional (Yogi can choose to stay or not)"
                  defaultValue={false}
                  component={SwitchFieldFF}
                  disabled={values.accomodationNotProvided}
                />
              </div>
              <div style={styles.fieldRow}>
                <Field
                  type="checkbox"
                  name="disabled"
                  label="Disable Retreat"
                  defaultValue={false}
                  component={SwitchFieldFF}
                />
              </div>
              <div style={styles.fieldRow}>
                {store.metadata.requestStates.supportingError && (
                  <NoticeBox error title="Supporting metadata unavailable">
                    {store.metadata.requestStates.supportingError}
                  </NoticeBox>
                )}
              </div>
              <div style={styles.fieldRow}>
                {error && (
                  <NoticeBox error title="Retreat creation failed">
                    {error?.details?.response?.errorReports
                      ?.map((report) => report.message)
                      .join(",")}
                  </NoticeBox>
                )}
              </div>
            </ModalContent>
            <ModalActions>
              <ButtonStrip end>
                <Button
                  onClick={() => {
                    form.reset();
                    onCancel();
                  }}
                  disabled={submitting}
                  secondary
                >
                  Cancel
                </Button>
                <Button
                  primary
                  type="submit"
                  loading={submitting || loading}
                  disabled={submitting || loading}
                  onClick={handleSubmit}
                >
                  {retreat ? "Update" : "Create"}
                </Button>
              </ButtonStrip>
            </ModalActions>
          </Modal>
        </form>
      )}
    </Form>
  );
});

export default RetreatModel;
