import {
  DHIS2_RETREAT_ATTRIBUTE_ACCOMMODATION_NOT_PROVIDED,
  DHIS2_RETREAT_ATTRIBUTE_ACCOMMODATION_OPTIONAL,
  DHIS2_RETREAT_ATTRIBUTE_PRIVATE,
  DHIS2_RETREAT_CLERGY_ONLY_ATTRIBUTE,
  DHIS2_RETREAT_CODE_ATTRIBUTE,
  DHIS2_RETREAT_DATE_ATTRIBUTE,
  DHIS2_RETREAT_DISABLED_ATTRIBUTE,
  DHIS2_RETREAT_LOCATION_ATTRIBUTE,
  DHIS2_RETREAT_MEDIUM_ATTRIBUTE,
  DHIS2_RETREAT_NO_OF_DAYS_ATTRIBUTE,
  DHIS2_RETREAT_TOTAL_YOGIS_ATTRIBUTE,
  DHIS2_RETREAT_TYPE_ATTRIBUTE,
} from "../dhis2";

export const generateRetreatName = (date, locationName) => {
  if (!date || !locationName) return "";
  return `${new Date(date)
    .toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    })
    .replace(",", "")} ${locationName}`;
};

export const mapRetreatToInitialValues = (retreat, editData) => {
  if (!retreat || !editData) return {};
  const attrs = editData.option.attributeValues;
  const getValue = (id) => attrs.find((a) => a.attribute.id === id)?.value;
  const getBoolValue = (id) => getValue(id) === "true";

  const name = editData.option.name;
  const date = getValue(DHIS2_RETREAT_DATE_ATTRIBUTE);
  const locationName = editData.orgUnit?.displayName;

  const generatedName = generateRetreatName(date, locationName);
  const isAutoGenerated = !retreat || name === generatedName;

  return {
    autoGenerateName: isAutoGenerated,
    name: name,
    code: getValue(DHIS2_RETREAT_CODE_ATTRIBUTE),
    date: getValue(DHIS2_RETREAT_DATE_ATTRIBUTE)?.split("T")[0],
    noOfDays: getValue(DHIS2_RETREAT_NO_OF_DAYS_ATTRIBUTE),
    noOfYogis: getValue(DHIS2_RETREAT_TOTAL_YOGIS_ATTRIBUTE),
    retreatType: getValue(DHIS2_RETREAT_TYPE_ATTRIBUTE),
    location: editData.orgUnit,
    medium: getValue(DHIS2_RETREAT_MEDIUM_ATTRIBUTE),
    clergyOnly: getBoolValue(DHIS2_RETREAT_CLERGY_ONLY_ATTRIBUTE),
    privateRetreat: getBoolValue(DHIS2_RETREAT_ATTRIBUTE_PRIVATE),
    accomodationNotProvided: getBoolValue(
      DHIS2_RETREAT_ATTRIBUTE_ACCOMMODATION_NOT_PROVIDED,
    ),
    accomodationOptional: getBoolValue(
      DHIS2_RETREAT_ATTRIBUTE_ACCOMMODATION_OPTIONAL,
    ),
    disabled: getBoolValue(DHIS2_RETREAT_DISABLED_ATTRIBUTE),
  };
};

export const mapFormValuesToAttributeValues = (values) => {
  return [
    {
      attribute: { id: DHIS2_RETREAT_DATE_ATTRIBUTE },
      value: values.date,
    },
    {
      attribute: { id: DHIS2_RETREAT_LOCATION_ATTRIBUTE },
      value: values.location.id,
    },
    {
      attribute: { id: DHIS2_RETREAT_NO_OF_DAYS_ATTRIBUTE },
      value: values.noOfDays,
    },
    {
      attribute: { id: DHIS2_RETREAT_TOTAL_YOGIS_ATTRIBUTE },
      value: values.noOfYogis,
    },
    {
      attribute: { id: DHIS2_RETREAT_TYPE_ATTRIBUTE },
      value: values.retreatType,
    },
    {
      attribute: { id: DHIS2_RETREAT_DISABLED_ATTRIBUTE },
      value: values.disabled || false,
    },
    {
      attribute: { id: DHIS2_RETREAT_CODE_ATTRIBUTE },
      value: values.code,
    },
    {
      attribute: { id: DHIS2_RETREAT_MEDIUM_ATTRIBUTE },
      value: values.medium,
    },
    {
      attribute: { id: DHIS2_RETREAT_CLERGY_ONLY_ATTRIBUTE },
      value: values.clergyOnly,
    },
    {
      attribute: { id: DHIS2_RETREAT_ATTRIBUTE_PRIVATE },
      value: values.privateRetreat,
    },
    {
      attribute: { id: DHIS2_RETREAT_ATTRIBUTE_ACCOMMODATION_NOT_PROVIDED },
      value: values.accomodationNotProvided,
    },
    {
      attribute: { id: DHIS2_RETREAT_ATTRIBUTE_ACCOMMODATION_OPTIONAL },
      value: values.accomodationOptional,
    },
  ];
};
